targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
      injectable_generator:injectable_config_builder:
        generate_for:
          - lib/injector.dart
      # mockito|mockBuilder:
      #   generate_for:
      #     - test/**.dart
